import { NextRequest, NextResponse } from "next/server";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getCurrentWorkspace } from "@/lib/workspaces";

export interface DeadlineItem {
  id: string;
  type: "event" | "task";
  title: string;
  dueDate: string;
  status: string;
  isCompleted: boolean;
  completedAt: string | null;
  source: "generated" | "manual";
  sourceLabel: string;
  caseId: string | null;
  caseTitle: string | null;
  caseNumber: string | null;
  caseCounty: string | null;
  assignedAttorneyName: string | null;
  assignedParalegalName: string | null;
  relatedEventId: string | null;
  relatedTaskId: string | null;
  triggerEventId: string | null;
  triggerEventTitle: string | null;
  triggerEventType: string | null;
  priority: string | null;
  // Discovery-specific fields (null for non-discovery deadlines)
  discoveryItemId: string | null;
  discoveryType: string | null;
  discoveryDirection: string | null;
  extensionCount: number | null;
}

export interface TrialItem {
  id: string;
  title: string;
  startTime: string;
  caseId: string | null;
  caseTitle: string | null;
  caseNumber: string | null;
  caseCounty: string | null;
  assignedAttorneyName: string | null;
  relatedDeadlines: {
    id: string;
    title: string;
    dueDate: string | null;
    status: string;
    type: "event" | "task";
  }[];
}

function sourceLabel(
  triggerEventType: string | null,
  isAutoGenerated: boolean,
  hasGeneratedDeadline: boolean
): { source: "generated" | "manual"; sourceLabel: string } {
  if (triggerEventType === "TRIAL") return { source: "generated", sourceLabel: "Generated from Trial" };
  if (triggerEventType === "CASE_MANAGEMENT_CONFERENCE") return { source: "generated", sourceLabel: "Generated from CMC" };
  if (triggerEventType === "CONFERENCE") return { source: "generated", sourceLabel: "Generated from CMC" };
  if (isAutoGenerated && !hasGeneratedDeadline) return { source: "generated", sourceLabel: "Generated from Court Rule" };
  if (hasGeneratedDeadline) return { source: "generated", sourceLabel: "Auto-Generated" };
  return { source: "manual", sourceLabel: "Manual" };
}

export async function GET(request: NextRequest) {
  const currentUser = await requireUser();
  if (!currentUser) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { workspace, membership } = await getCurrentWorkspace(currentUser.id);
  if (!workspace || !membership) return NextResponse.json({ error: "No workspace" }, { status: 403 });

  const { searchParams } = new URL(request.url);
  const attorneyId = searchParams.get("attorneyId");
  const paralegalId = searchParams.get("paralegalId");
  const caseId = searchParams.get("caseId");
  const sourceFilter = searchParams.get("source"); // "generated" | "manual" | null
  const includeCompleted = searchParams.get("includeCompleted") === "true";

  // Permission filtering: ASSISTANT (non-admin) only sees their own deadlines
  const isAssistantOnly =
    membership.jobTitle === "ASSISTANT" &&
    membership.role !== "ADMIN" &&
    membership.role !== "OWNER";

  // Source A: Deadline Events
  const eventWhere: Record<string, unknown> = {
    eventType: "DEADLINE",
    OR: [
      { workspaceId: workspace.id },
      { userId: currentUser.id, workspaceId: null },
    ],
    caseRef: {
      status: { notIn: ["CLOSED", "ARCHIVED"] },
    },
  };

  if (!includeCompleted) {
    eventWhere.status = { notIn: ["COMPLETED", "CANCELLED"] };
  }

  if (caseId) eventWhere.caseId = caseId;
  if (attorneyId) eventWhere.assignedAttorneyId = attorneyId;

  if (isAssistantOnly) {
    eventWhere.assignedAttorneyId = currentUser.id;
  }

  const deadlineEvents = await prisma.event.findMany({
    where: eventWhere as never,
    include: {
      caseRef: { select: { id: true, title: true, caseNumber: true, status: true, county: true } },
      assignedAttorney: { select: { id: true, firstName: true, lastName: true } },
      generatedDeadline: {
        include: { triggerEvent: { select: { id: true, title: true, eventType: true } } },
      },
      discoveryLinked: {
        select: {
          id: true,
          discoveryType: true,
          direction: true,
          extensions: { select: { id: true } },
        },
      },
    },
    orderBy: { startTime: "asc" },
  });

  // Source B: Tasks with due dates
  const taskWhere: Record<string, unknown> = {
    workspaceId: workspace.id,
    dueDate: { not: null },
    caseRef: {
      status: { notIn: ["CLOSED", "ARCHIVED"] },
    },
  };

  if (!includeCompleted) {
    taskWhere.status = { not: "DONE" };
  }

  if (caseId) taskWhere.caseId = caseId;

  const deadlineTasks = await prisma.task.findMany({
    where: taskWhere as never,
    include: {
      caseRef: { select: { id: true, title: true, caseNumber: true, status: true, county: true } },
      assignees: {
        include: {
          member: {
            select: {
              id: true,
              jobTitle: true,
              user: { select: { id: true, firstName: true, lastName: true } },
            },
          },
        },
      },
      generatedDeadline: {
        include: { triggerEvent: { select: { id: true, title: true, eventType: true } } },
      },
    },
    orderBy: { dueDate: "asc" },
  });

  // Build deadline items from events
  const eventItems: DeadlineItem[] = deadlineEvents.map((ev) => {
    const gd = ev.generatedDeadline;
    const dl = ev.discoveryLinked;
    const triggerType = gd?.triggerEvent?.eventType ?? null;
    const isDiscovery = !!dl;
    const { source, sourceLabel: sl } = isDiscovery
      ? { source: "generated" as const, sourceLabel: "Discovery" }
      : sourceLabel(triggerType, false, !!gd);

    const attorneyName = ev.assignedAttorney
      ? [ev.assignedAttorney.firstName, ev.assignedAttorney.lastName].filter(Boolean).join(" ") || null
      : null;

    return {
      id: ev.id,
      type: "event" as const,
      title: ev.title,
      dueDate: ev.startTime.toISOString(),
      status: ev.status,
      isCompleted: ev.status === "COMPLETED",
      completedAt: ev.status === "COMPLETED" ? ev.updatedAt.toISOString() : null,
      source,
      sourceLabel: sl,
      caseId: ev.caseId ?? null,
      caseTitle: ev.caseRef?.title ?? null,
      caseNumber: ev.caseRef?.caseNumber ?? null,
      caseCounty: ev.caseRef?.county ?? null,
      assignedAttorneyName: attorneyName,
      assignedParalegalName: null,
      relatedEventId: null,
      relatedTaskId: gd?.generatedTaskId ?? null,
      triggerEventId: gd?.triggerEvent?.id ?? null,
      triggerEventTitle: gd?.triggerEvent?.title ?? null,
      triggerEventType: triggerType,
      priority: null,
      discoveryItemId: dl?.id ?? null,
      discoveryType: dl?.discoveryType ?? null,
      discoveryDirection: dl?.direction ?? null,
      extensionCount: dl ? dl.extensions.length : null,
    };
  });

  // Build deadline items from tasks
  let taskItems: DeadlineItem[] = deadlineTasks.map((task) => {
    const gd = task.generatedDeadline;
    const triggerType = gd?.triggerEvent?.eventType ?? null;
    const { source, sourceLabel: sl } = sourceLabel(triggerType, task.isAutoGenerated, !!gd);

    const attorneyAssignee = task.assignees.find((a) => a.member.jobTitle === "ATTORNEY");
    const paralegalAssignee = task.assignees.find((a) => a.member.jobTitle === "PARALEGAL");

    const attorneyName = attorneyAssignee
      ? [attorneyAssignee.member.user.firstName, attorneyAssignee.member.user.lastName].filter(Boolean).join(" ") || null
      : null;
    const paralegalName = paralegalAssignee
      ? [paralegalAssignee.member.user.firstName, paralegalAssignee.member.user.lastName].filter(Boolean).join(" ") || null
      : null;

    return {
      id: task.id,
      type: "task" as const,
      title: task.title,
      dueDate: task.dueDate!.toISOString(),
      status: task.status,
      isCompleted: task.status === "DONE",
      completedAt: task.completedAt?.toISOString() ?? null,
      source,
      sourceLabel: sl,
      caseId: task.caseId ?? null,
      caseTitle: task.caseRef?.title ?? null,
      caseNumber: task.caseRef?.caseNumber ?? null,
      caseCounty: task.caseRef?.county ?? null,
      assignedAttorneyName: attorneyName,
      assignedParalegalName: paralegalName,
      relatedEventId: task.eventId ?? null,
      relatedTaskId: null,
      triggerEventId: gd?.triggerEvent?.id ?? null,
      triggerEventTitle: gd?.triggerEvent?.title ?? null,
      triggerEventType: triggerType,
      priority: task.priority,
      discoveryItemId: null,
      discoveryType: null,
      discoveryDirection: null,
      extensionCount: null,
    };
  });

  // Filter tasks for ASSISTANT
  if (isAssistantOnly) {
    taskItems = taskItems.filter((t) =>
      deadlineTasks.find((dt) => dt.id === t.id)?.assignees.some(
        (a) => a.member.user.id === currentUser.id
      )
    );
  }

  // Filter by paralegalId
  let allDeadlines = [...eventItems, ...taskItems];

  if (paralegalId) {
    allDeadlines = allDeadlines.filter((d) => {
      const task = deadlineTasks.find((t) => t.id === d.id);
      if (!task) return false;
      return task.assignees.some(
        (a) => a.member.jobTitle === "PARALEGAL" && a.member.user.id === paralegalId
      );
    });
  }

  // Filter by source
  if (sourceFilter === "generated") {
    allDeadlines = allDeadlines.filter((d) => d.source === "generated");
  } else if (sourceFilter === "manual") {
    allDeadlines = allDeadlines.filter((d) => d.source === "manual");
  }

  // Source C: Upcoming Trials
  const now = new Date();
  const sixtyDaysOut = new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000);

  const upcomingTrials = await prisma.event.findMany({
    where: {
      eventType: "TRIAL",
      startTime: { gte: now, lte: sixtyDaysOut },
      OR: [
        { workspaceId: workspace.id },
        { userId: currentUser.id, workspaceId: null },
      ],
    },
    include: {
      caseRef: { select: { id: true, title: true, caseNumber: true, status: true, county: true } },
      assignedAttorney: { select: { id: true, firstName: true, lastName: true } },
      triggeredDeadlines: {
        include: {
          generatedEvent: { select: { id: true, title: true, startTime: true, status: true } },
          generatedTask: { select: { id: true, title: true, dueDate: true, status: true } },
        },
      },
    },
    orderBy: { startTime: "asc" },
  });

  const trials: TrialItem[] = upcomingTrials.map((trial) => {
    const attorneyName = trial.assignedAttorney
      ? [trial.assignedAttorney.firstName, trial.assignedAttorney.lastName].filter(Boolean).join(" ") || null
      : null;

    const relatedDeadlines = trial.triggeredDeadlines.flatMap((gd) => {
      const items = [];
      if (gd.generatedEvent) {
        items.push({
          id: gd.generatedEvent.id,
          title: gd.generatedEvent.title,
          dueDate: gd.generatedEvent.startTime.toISOString(),
          status: gd.generatedEvent.status,
          type: "event" as const,
        });
      }
      if (gd.generatedTask) {
        items.push({
          id: gd.generatedTask.id,
          title: gd.generatedTask.title,
          dueDate: gd.generatedTask.dueDate?.toISOString() ?? null,
          status: gd.generatedTask.status,
          type: "task" as const,
        });
      }
      return items;
    });

    return {
      id: trial.id,
      title: trial.title,
      startTime: trial.startTime.toISOString(),
      caseId: trial.caseId ?? null,
      caseTitle: trial.caseRef?.title ?? null,
      caseNumber: trial.caseRef?.caseNumber ?? null,
      caseCounty: trial.caseRef?.county ?? null,
      assignedAttorneyName: attorneyName,
      relatedDeadlines,
    };
  });

  return NextResponse.json({ deadlines: allDeadlines, trials });
}
