-- AlterEnum
ALTER TYPE "CaseStatus" ADD VALUE 'DISCOVERY';
ALTER TYPE "CaseStatus" ADD VALUE 'ARBITRATION';
ALTER TYPE "CaseStatus" ADD VALUE 'UIM_ARBITRATION';
ALTER TYPE "CaseStatus" ADD VALUE 'UM_ARBITRATION';
ALTER TYPE "CaseStatus" ADD VALUE 'SERVED';
ALTER TYPE "CaseStatus" ADD VALUE 'PARTIALLY_SERVED';
ALTER TYPE "CaseStatus" ADD VALUE 'PENDING_SERVICE';
ALTER TYPE "CaseStatus" ADD VALUE 'SENT_FOR_SERVICE';
ALTER TYPE "CaseStatus" ADD VALUE 'SERVICE_POSTPONED';
ALTER TYPE "CaseStatus" ADD VALUE 'PENDING_RFD';
ALTER TYPE "CaseStatus" ADD VALUE 'SETTLED';
ALTER TYPE "CaseStatus" ADD VALUE 'DISBURSEMENT';
ALTER TYPE "CaseStatus" ADD VALUE 'LIEN_NEGOTIATIONS';
ALTER TYPE "CaseStatus" ADD VALUE 'DISMISSAL_FILED';
