import { NextRequest, NextResponse } from "next/server";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { canDelete, canEdit, getCurrentWorkspace } from "@/lib/workspaces";
import { TASK_INCLUDE } from "../route";
import { addTimelineEntry } from "@/lib/case-timeline";
import { pushTaskToGoogle, deleteTaskFromGoogle } from "@/lib/task-google-sync";
import { sendTaskAssignedEmails } from "@/lib/email-notifications";

async function getTaskForWorkspace(id: string, workspaceId: string) {
  return prisma.task.findFirst({ where: { id, workspaceId }, include: TASK_INCLUDE });
}

// PATCH /api/tasks/[id]
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const currentUser = await requireUser();
  if (!currentUser) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { workspace, membership } = await getCurrentWorkspace(currentUser.id);
  if (!workspace || !membership) return NextResponse.json({ error: "No workspace" }, { status: 403 });
  if (!canEdit(membership.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { id } = await params;
  const existing = await getTaskForWorkspace(id, workspace.id);
  if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const body = await request.json() as {
    title?: string;
    description?: string;
    status?: string;
    priority?: string;
    dueDate?: string | null;
    caseId?: string | null;
    eventId?: string | null;
    assigneeIds?: string[];
  };

  const STATUSES   = ["TODO", "IN_PROGRESS", "DONE"];
  const PRIORITIES = ["LOW", "MEDIUM", "HIGH", "URGENT"];

  const completedAt =
    body.status === "DONE" && existing.status !== "DONE"   ? new Date()
    : body.status !== "DONE" && existing.status === "DONE" ? null
    : existing.completedAt;

  // Handle assignee diff if provided
  let newlyAddedMemberIds: string[] = [];
  if (body.assigneeIds !== undefined) {
    const incomingIds = body.assigneeIds.filter(Boolean);

    // Validate they belong to the workspace
    if (incomingIds.length > 0) {
      const valid = await prisma.workspaceMember.findMany({
        where: { workspaceId: workspace.id, id: { in: incomingIds } },
        select: { id: true },
      });
      const validSet = new Set(valid.map((m) => m.id));
      const invalid = incomingIds.filter((mid) => !validSet.has(mid));
      if (invalid.length > 0)
        return NextResponse.json({ error: "Invalid assignee IDs" }, { status: 400 });
    }

    const currentIds = existing.assignees.map((a) => a.member.id);
    const toAdd    = incomingIds.filter((mid) => !currentIds.includes(mid));
    const toRemove = currentIds.filter((mid) => !incomingIds.includes(mid));

    if (toRemove.length > 0) {
      await prisma.taskAssignee.deleteMany({
        where: { taskId: id, memberId: { in: toRemove } },
      });
    }
    if (toAdd.length > 0) {
      await prisma.taskAssignee.createMany({
        data: toAdd.map((memberId) => ({ taskId: id, memberId })),
        skipDuplicates: true,
      });
    }
    newlyAddedMemberIds = toAdd;
  }

  // If this is a generated task and its due date is being changed by the user, mark userModified
  if (body.dueDate !== undefined && existing.isAutoGenerated) {
    const existingDue = existing.dueDate ? new Date(existing.dueDate).getTime() : null;
    const incomingDue = body.dueDate ? new Date(body.dueDate).getTime() : null;
    if (existingDue !== incomingDue) {
      await prisma.generatedDeadline.updateMany({
        where: { generatedTaskId: id },
        data: { userModified: true },
      });
    }
  }

  const task = await prisma.task.update({
    where: { id },
    data: {
      ...(body.title       !== undefined ? { title:       body.title.trim() }                                     : {}),
      ...(body.description !== undefined ? { description: body.description?.trim() || null }                      : {}),
      ...(body.status      !== undefined && STATUSES.includes(body.status)   ? { status:   body.status   as never } : {}),
      ...(body.priority    !== undefined && PRIORITIES.includes(body.priority) ? { priority: body.priority as never } : {}),
      ...(body.dueDate     !== undefined ? { dueDate:  body.dueDate  ? new Date(body.dueDate) : null }            : {}),
      ...(body.caseId      !== undefined ? { caseId:   body.caseId  || null }                                     : {}),
      ...(body.eventId     !== undefined ? { eventId:  body.eventId || null }                                     : {}),
      completedAt,
    },
    include: TASK_INCLUDE,
  });

  if (task.status === "DONE") {
    await prisma.notification.deleteMany({
      where: { workspaceId: workspace.id, taskId: task.id },
    });
    if (task.caseId) {
      void addTimelineEntry({
        caseId: task.caseId,
        workspaceId: workspace.id,
        actorUserId: currentUser.id,
        type: "task.completed",
        title: `Task completed: ${task.title}`,
        metadata: { taskId: task.id },
      });
    }
    // Remove from Google Calendar when marked done
    void deleteTaskFromGoogle(currentUser.id, task.id);
  } else if (body.status !== undefined && existing.status === "DONE" && body.status !== "DONE") {
    // Moved back from DONE — re-push to Google Calendar if it has a due date
    if (task.dueDate) {
      void pushTaskToGoogle(currentUser.id, {
        id: task.id,
        title: task.title,
        dueDate: task.dueDate,
        priority: task.priority,
        caseRef: task.caseRef ?? null,
      });
    }
  } else if (body.dueDate !== undefined) {
    // Due date changed — re-push to Google Calendar (only if this user had it synced)
    const existingSync = await prisma.userTaskGoogleSync.findUnique({
      where: { taskId_userId: { taskId: task.id, userId: currentUser.id } },
    });
    if (existingSync) {
      // Delete old event first, then push new one
      void deleteTaskFromGoogle(currentUser.id, task.id).then(() => {
        if (task.dueDate) {
          void pushTaskToGoogle(currentUser.id, {
            id: task.id,
            title: task.title,
            dueDate: task.dueDate,
            priority: task.priority,
            caseRef: task.caseRef ?? null,
          });
        }
      });
    } else if (task.dueDate) {
      void pushTaskToGoogle(currentUser.id, {
        id: task.id,
        title: task.title,
        dueDate: task.dueDate,
        priority: task.priority,
        caseRef: task.caseRef ?? null,
      });
    }
  }

  // Notify newly added assignees
  if (task.status !== "DONE" && newlyAddedMemberIds.length > 0) {
    const assigner = currentUser;
    const assignerName = [assigner.firstName, assigner.lastName].filter(Boolean).join(" ") || assigner.email;

    const members = await prisma.workspaceMember.findMany({
      where: { id: { in: newlyAddedMemberIds } },
      select: { id: true, userId: true },
    });

    const caseTitle = task.caseRef?.title ?? null;
    const notifBody = [
      caseTitle ? `Case: ${caseTitle}` : null,
      `Assigned by: ${assignerName}`,
    ].filter(Boolean).join("\n");

    await prisma.notification.createMany({
      data: members.map((m) => ({
        userId:      m.userId,
        workspaceId: workspace.id,
        type:        "TASK_ASSIGNED" as never,
        title:       `Task Assigned: ${task.title}`,
        body:        notifBody || null,
        taskId:      task.id,
        caseId:      task.caseId ?? null,
      })),
      skipDuplicates: true,
    });
    await sendTaskAssignedEmails(task.id, assignerName);
  }

  return NextResponse.json({ task });
}

// DELETE /api/tasks/[id]
export async function DELETE(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const currentUser = await requireUser();
  if (!currentUser) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { workspace, membership } = await getCurrentWorkspace(currentUser.id);
  if (!workspace || !membership) return NextResponse.json({ error: "No workspace" }, { status: 403 });
  if (!canDelete(membership.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { id } = await params;
  const existing = await getTaskForWorkspace(id, workspace.id);
  if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 });

  await prisma.notification.deleteMany({
    where: { workspaceId: workspace.id, taskId: id },
  });
  // Awaited (not fire-and-forget): deleting the task cascades to
  // UserTaskGoogleSync, so this must read the sync row before that happens.
  await deleteTaskFromGoogle(currentUser.id, id);
  await prisma.task.delete({ where: { id } });
  return NextResponse.json({ ok: true });
}
