-- Add isAutoGenerated flag to Task
ALTER TABLE "Task" ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- GeneratedDeadline table
CREATE TABLE "GeneratedDeadline" (
  "id"               TEXT         NOT NULL,
  "workspaceId"      TEXT         NOT NULL,
  "triggerEventId"   TEXT         NOT NULL,
  "ruleKey"          TEXT         NOT NULL,
  "generatedEventId" TEXT,
  "generatedTaskId"  TEXT,
  "userModified"     BOOLEAN      NOT NULL DEFAULT false,
  "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "GeneratedDeadline_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "GeneratedDeadline_generatedEventId_key" ON "GeneratedDeadline"("generatedEventId");
CREATE UNIQUE INDEX "GeneratedDeadline_generatedTaskId_key"  ON "GeneratedDeadline"("generatedTaskId");
CREATE UNIQUE INDEX "GeneratedDeadline_triggerEventId_ruleKey_key" ON "GeneratedDeadline"("triggerEventId", "ruleKey");
CREATE INDEX "GeneratedDeadline_workspaceId_idx"      ON "GeneratedDeadline"("workspaceId");
CREATE INDEX "GeneratedDeadline_triggerEventId_idx"   ON "GeneratedDeadline"("triggerEventId");
CREATE INDEX "GeneratedDeadline_generatedEventId_idx" ON "GeneratedDeadline"("generatedEventId");
CREATE INDEX "GeneratedDeadline_generatedTaskId_idx"  ON "GeneratedDeadline"("generatedTaskId");

ALTER TABLE "GeneratedDeadline"
  ADD CONSTRAINT "GeneratedDeadline_workspaceId_fkey"
  FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "GeneratedDeadline"
  ADD CONSTRAINT "GeneratedDeadline_triggerEventId_fkey"
  FOREIGN KEY ("triggerEventId") REFERENCES "Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "GeneratedDeadline"
  ADD CONSTRAINT "GeneratedDeadline_generatedEventId_fkey"
  FOREIGN KEY ("generatedEventId") REFERENCES "Event"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "GeneratedDeadline"
  ADD CONSTRAINT "GeneratedDeadline_generatedTaskId_fkey"
  FOREIGN KEY ("generatedTaskId") REFERENCES "Task"("id") ON DELETE SET NULL ON UPDATE CASCADE;
